name: Build Siso-ng (All Platforms)

on:
  workflow_dispatch:
    inputs:
      linux:
        description: 'Build Linux (amd64)'
        type: boolean
        default: true
      windows:
        description: 'Build Windows (32/64-bit)'
        type: boolean
        default: true
      macos:
        description: 'Build macOS (x64/arm64)'
        type: boolean
        default: true

jobs:
  linux:
    name: Linux amd64
    if: ${{ inputs.linux }}
    uses: ./.github/workflows/build-linux.yml

  windows:
    name: Windows 32/64 Bit
    if: ${{ inputs.windows }}
    uses: ./.github/workflows/build-win.yml

  macos:
    name: MacOS x64/ARM64
    if: ${{ inputs.macos }}
    uses: ./.github/workflows/build-mac.yml
